# Uncomment the next line to define a global platform for your project
platform :ios, '10.2'

target 'TSApp' do
  pod 'AppCenter/Crashes', '1.13.0'
  pod 'AppCenter/Analytics', '1.13.0'
  pod 'AppCenterReactNativeShared', '1.12.0'

  target 'TSAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TSApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TSApp-tvOS

  target 'TSApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
